name: Dependabot Auto-Merge

on:
  pull_request:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          
      - name: Get commit hash
        id: commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Report commit hash
        run: echo "Auto-merge processed for dependabot PR at commit ${{ steps.commit.outputs.hash }} on dev branch"
